//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingCars
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSeller
    {
        public int Id { get; set; }
        public string Seller { get; set; }
        public string Car { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
